name: sikshya
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  bloc: ^8.1.2
  chewie: ^1.7.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^6.0.0
  get_it: ^7.6.4
  iconly: ^1.0.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  lottie: ^2.7.0
  open_file: ^3.3.2
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.2
  url_launcher: ^6.2.0
  video_thumbnail: ^0.5.3
  youtube_metadata: ^1.0.1
  go_router: ^12.0.1
  rive: ^0.12.2
  hexcolor: ^3.0.1
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  firebase_ui_auth: ^1.7.0
  firebase_storage: ^11.4.1

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/
    - assets/animation/
    - assets/vectors/
    - assets/images/background/

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
